name: _Build

on:    
  workflow_dispatch:
    inputs:
      os:
        description: 'An Operating System'
        required: true
        type: choice
        options:
          - Linux
          - Windows
          - macOS
      env:
        description: 'An Environment'
        required: true
        type: choice
        options:
          - Development
          - Production

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}-latest
    
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Update haxelib
        run: haxelib --global update haxelib --quiet

      - name: Install dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install actuate --quiet
          haxelib install feathersui --quiet
      
      - name: Map GitHub OS to Haxe OS
        uses: dkershner6/switch-case-action@v1
        id: haxe-os
        with:
          conditionals-with-values: |
            ${{ github.event.inputs.os == 'Linux' }} => linux
            ${{ github.event.inputs.os == 'Windows' }} => windows
            ${{ github.event.inputs.os == 'macOS' }} => mac

      - name: Map Env to Haxe debug flag
        uses: dkershner6/switch-case-action@v1
        id: haxe-debug
        with:
          conditionals-with-values: |
            ${{ github.event.inputs.env == 'Production' }} => ''
            ${{ github.event.inputs.env == 'Development' }} => '-debug'

      - name: Build
        run: haxelib run openfl build project.xml ${{ steps.haxe-os.outputs.value }} ${{ steps.haxe-debug.outputs.value }}