name: _Build

on:    
  workflow_dispatch:
    inputs:
      os:
        description: 'An Operating System'
        required: true
        type: choice
        options:
          - ubuntu
          - windows
          - macos
      env:
        description: 'An Environment'
        required: true
        type: choice
        options:
          - development
          - production

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}-latest
    
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Update haxelib
        run: haxelib --global update haxelib --quiet

      - name: Install dependencies
        uses: ./install-dependencies
      
      - name: Map GitHub OS to Haxe OS
        uses: spilchen/switch-case-action@v2
        id: haxe-os
        with:
          conditionals-with-values: |
            ${{ github.event.inputs.os == 'ubuntu' }} => linux
            ${{ github.event.inputs.os == 'windows' }} => windows
            ${{ github.event.inputs.os == 'macos' }} => mac

      - name: Map Env to Haxe debug flag
        uses: spilchen/switch-case-action@v2
        id: haxe-env-flag
        with:
          conditionals-with-values: |
            ${{ github.event.inputs.env == 'production' }} => -release
            ${{ github.event.inputs.env == 'development' }} => -debug

      - name: Build
        run: >
          haxelib run openfl build 
          project.xml 
          ${{ steps.haxe-os.outputs.value }} 
          ${{ steps.haxe-env-flag.outputs.value }} 
          -clean

      - name: Map GitHub OS to Haxe OS
        uses: spilchen/switch-case-action@v2
        id: haxe-platform-dir
        with:
          conditionals-with-values: |
            ${{ github.event.inputs.os == 'ubuntu' }} => linux
            ${{ github.event.inputs.os == 'windows' }} => windows
            ${{ github.event.inputs.os == 'macos' }} => macos

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.haxe-platform-dir.outputs.value }}-${{ github.event.inputs.env }}-bin
          path: bin/${{ steps.haxe-platform-dir.outputs.value }}/bin/