name: _Build

on:    
  workflow_dispatch:
    inputs:
      os:
        description: 'An Operating System'
        required: true
        type: choice
        options:
          - linux
          - windows
          - mac
      env:
        description: 'An Environment'
        required: true
        type: choice
        options:
          - development
          - production

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}-latest
    
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Update haxelib
        run: haxelib --global update haxelib --quiet

      - name: Install dependencies
        run: |
          haxelib install openfl --quiet
          haxelib install actuate --quiet
          haxelib install feathersui --quiet

      - name: Build
        run: haxelib run lime build project.xml windows -debug