name: _Build

on:    
  workflow_dispatch:
    inputs:
      os:
        description: 'An Operating System'
        required: true
        type: choice
        options:
          - Linux
          - Windows
          - macOS
      env:
        description: 'An Environment'
        required: true
        type: choice
        options:
          - Development
          - Production

jobs:
  build:
    runs-on: linux-latest
    
    steps:    
      - name: Print error
        run: echo 'Error - placeholder workflow to be run from feature branch'